#!/bin/bash
echo "=================================================="
echo "    JBuild Compile with Auto-Detected Config"
echo "=================================================="
echo ""
echo "Configuracion auto-detectada: build.jbuild"
echo "Tipo: Multi-Module Enterprise (476 lineas)"
echo ""
echo "Compilando proyecto multi-modulo..."
echo "python3 jbuild_cli.py compile"
echo ""
echo "Nota: Este comando usarıa automaticamente build.jbuild"
echo "para compilar el proyecto multi-modulo enterprise."
#!/bin/bash
echo "=================================================="
echo "    JBuild Compile with Auto-Detected Config"
echo "=================================================="
echo ""
echo "Configuracion auto-detectada: build.jbuild"
echo "Tipo: Multi-Module Enterprise (476 lineas)"
echo ""
echo "Compilando proyecto multi-modulo..."
echo "python3 jbuild_cli.py compile"
echo ""
echo "Nota: Este comando usaria automaticamente build.jbuild"
echo "para compilar el proyecto multi-modulo enterprise."